import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateRoleTable1778968443497 implements MigrationInterface {
    name = 'CreateRoleTable1778968443497'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_tasks_project"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_attendance_user"`);
        await queryRunner.query(`ALTER TABLE "standups" DROP CONSTRAINT "FK_standups_user"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_user_role"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" DROP CONSTRAINT "FK_correction_user"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" DROP CONSTRAINT "FK_correction_attendance"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" DROP CONSTRAINT "FK_correction_reviewer"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_project_members_project"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_project_members_user"`);
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_task"`);
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attendance_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_standups_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_correction_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_correction_attendance"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_description"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_description" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum" RENAME TO "task_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('inProgress', 'inReview', 'completed', 'critical')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."tasks_status_enum" USING "status"::"text"::"public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'inProgress'`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "standups" ALTER COLUMN "yesterdayWork" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "permissions_pkey"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_pkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "permission_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "permission_id" integer`);
        await queryRunner.query(`ALTER TYPE "public"."correction_status_enum" RENAME TO "correction_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_corrections_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ALTER COLUMN "status" TYPE "public"."attendance_corrections_status_enum" USING "status"::"text"::"public"."attendance_corrections_status_enum"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."correction_status_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e128bc41a4a2e474ec654e50f9" ON "attendance" ("userId", "date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_50856437a5f810d10ecc4975ed" ON "standups" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5729113570c20c7e214cf3f58" ON "project_members" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e89aae80e010c2faa72e6a49ce" ON "project_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b1600551063c485554bca74c1" ON "task_assignees" ("taskId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1f7dbf3fd1b02451882ea7c7b" ON "task_assignees" ("userId") `);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_466e85b813d871bfb693f443528" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standups" ADD CONSTRAINT "FK_78014ba0c373ad196448f950563" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ADD CONSTRAINT "FK_0e5d5e8275ed29e77c94e8fd409" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ADD CONSTRAINT "FK_08ec9e14b59c58adc1c6cf76a19" FOREIGN KEY ("attendanceId") REFERENCES "attendance"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ADD CONSTRAINT "FK_631d956c3d2cac24872dac843e4" FOREIGN KEY ("reviewedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_8b1600551063c485554bca74c13" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_e1f7dbf3fd1b02451882ea7c7b4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_e1f7dbf3fd1b02451882ea7c7b4"`);
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_8b1600551063c485554bca74c13"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" DROP CONSTRAINT "FK_631d956c3d2cac24872dac843e4"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" DROP CONSTRAINT "FK_08ec9e14b59c58adc1c6cf76a19"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" DROP CONSTRAINT "FK_0e5d5e8275ed29e77c94e8fd409"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "standups" DROP CONSTRAINT "FK_78014ba0c373ad196448f950563"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_466e85b813d871bfb693f443528"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1f7dbf3fd1b02451882ea7c7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b1600551063c485554bca74c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89aae80e010c2faa72e6a49ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5729113570c20c7e214cf3f58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50856437a5f810d10ecc4975ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e128bc41a4a2e474ec654e50f9"`);
        await queryRunner.query(`CREATE TYPE "public"."correction_status_enum_old" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ALTER COLUMN "status" TYPE "public"."correction_status_enum_old" USING "status"::"text"::"public"."correction_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."attendance_corrections_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."correction_status_enum_old" RENAME TO "correction_status_enum"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "permission_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "permission_id" uuid`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_84059017c90bfcb701b8fa42297"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "PK_920331560282b8bd21bb02290df"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "standups" ALTER COLUMN "yesterdayWork" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum_old" AS ENUM('inProgress', 'inReview', 'completed', 'critical')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."task_status_enum_old" USING "status"::"text"::"public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'inProgress'`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum_old" RENAME TO "task_status_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_description"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_description" text`);
        await queryRunner.query(`CREATE INDEX "IDX_correction_attendance" ON "attendance_corrections" ("attendanceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_correction_user" ON "attendance_corrections" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_standups_user_date" ON "standups" ("date", "userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_attendance_user_date" ON "attendance" ("date", "userId") `);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_task" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_project_members_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_project_members_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ADD CONSTRAINT "FK_correction_reviewer" FOREIGN KEY ("reviewedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ADD CONSTRAINT "FK_correction_attendance" FOREIGN KEY ("attendanceId") REFERENCES "attendance"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_corrections" ADD CONSTRAINT "FK_correction_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_user_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standups" ADD CONSTRAINT "FK_standups_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_attendance_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_tasks_project" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
